name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Install dbdocs/cli
        run: sudo npm install -g @dbml/cli

      - name: Check dbdocs
        run: dbdocs

      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQ3NDYwLCJ0b2tlbiI6ImI0ODBlMjViNGE5NWExZWZhNzNjNjQzZGExNTkxOGMyIiwiaWF0IjoxNzY0NzE2NjYxfQ.M55-4Lfd_pogzdJQaKKc7Ov6T6NgF6Cn0jN1LPqOZ7s
        run: |
          sql2dbml --mysql db/init.sql -o dbmlupdate.dbml
          dbdocs build dbmlupdate.dbml --project Project V Database
